services:
  hugo:
    image: hugomods/hugo:debian-nightly-non-root
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    working_dir: /src
    command: hugo server --bind=0.0.0.0 --buildDrafts --buildFuture --disableFastRender